export type RootStackParamList = {
  Splash: undefined;
  Onboarding: undefined;
  Welcome: undefined;
  Login: undefined;
  SignUp: undefined;
  ForgotPassword: undefined;
  VerificationCode: {email: string};
  ResetPassword: undefined;
  PasswordSuccess: undefined;
  GameSelection: undefined;
  FinancialInput: {selectedGames: string[]};
  Home: {newExpense?: number} | undefined;
  AddExpenseGame: undefined;
  CategorySelection: {gameId: string; gameName: string};
  AddAmount: {gameId: string; gameName: string; category: string};
  AddGame: undefined;
  Goals: undefined;
  Analysis: undefined;
  Distributions: undefined;
  SmartSuggestions: undefined;
  TransactionCalendar: undefined;
  Progress: undefined;
  Leaderboard: undefined;
  Profile: undefined;
  EditProfile: undefined;
  AddFriend: undefined;
  HelpSupport: undefined;
  Settings: undefined;
  About: undefined;
};
